---
title: "Dashboard play"
author: "O.P"
date: "2022-08-23"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    orientation: rows
    vertical_layout: scroll
---

```{r Set up}
library(ggplot2)
library(shiny)
library(plotly)
library(dplyr)
library(tidyverse)
library(multcompView)
library(plotrix)

country_info <- readRDS("country.info.rds")
life_expect_df_2 <- readRDS("life.expect.df.2.RDS")
life_expect_df <- readRDS("life.expect.df.RDS")
dt3 <- readRDS("dt3.RDS")
cld3 <- readRDS("cld3.RDS")

# Summarize data for the scatter plots
region_mort_tb1 <- country_info %>%
  dplyr::select(country, region, life_expectancy_birth, mortality_rate)

region_mort_tb2 <- region_mort_tb1 %>%
  # Create new column with categorization of life expectancy at birth
  mutate(life_expect_class = ifelse(life_expectancy_birth >= 74.76, "High",
                                  ifelse(life_expectancy_birth >= 70.07, "High-moderate",
                                         ifelse(life_expectancy_birth >= 65.54, "Moderate",
                                                ifelse(life_expectancy_birth >= 59.70, "Low-moderate",
                                                       ifelse(life_expectancy_birth < 59.69, "Low", NA)))))) %>%
  # Filter out NA values
  drop_na(life_expect_class) %>%
  drop_na(mortality_rate)

# Make life expectancy classes into factors
life_expect_df$life_expect_class <- factor(life_expect_df$life_expect_class,
                                           levels = c("Low", "Low-moderate", "Moderate", "High-moderate","High"))

```

Sidebar {.sidebar}
======================================================================

Instructional text

Life Expectancy Data
======================================================================

Row
-----------------------------------------------------------------------

### **Chart 5:** Relationship Between COVID-19 Mortality Rate and Life Expectancy per Regions Globally
```{r}
# ggplotly(ggplot(region_mort_tb1, aes(text = paste("country: ", country),x=life_expectancy_birth, y=mortality_rate, color = region)) + geom_point() + facet_wrap(. ~ region, nrow = 2) + labs(y = "COVID-19 Mortality Rate", x = "Life Expectancy at Birth (years)"))

```
```{r Chart 5}
x1 <- ggplot(region_mort_tb1, aes(text = paste("country: ",country),x=life_expectancy_birth, y=mortality_rate, color = region)) + geom_point() + facet_wrap(.~ region, nrow = 2) + labs(y = "COVID-19 Mortality Rate", x = "Life Expectancy at Birth (years)") + theme_minimal()

x1 <- ggplotly(x1)

x1 %>%
  layout(showlegend = F)
```


Row 
-----------------------------------------------------------------------
### **Chart 6:** ANOVA Result Showing Multiple Comparisons of Relationship Between Mortality Rate and Life Expectancy Class
```{r}
# ggplotly(ggplot(dt3, aes(life_expect_class, mean_mortality_rate)) +
#       geom_bar(stat = "identity", aes(fill = mean_mortality_rate), show.legend = FALSE) +
#       geom_errorbar(aes(ymin = mean_mortality_rate - standard_error, ymax = mean_mortality_rate + standard_error), width = 0.2) +
#       labs(x = "Life Expectancy at Birth Class", y = "COVID-19 Mortality Rate") +
#       #      title = "Multiple Comparisons of Relationship Between Mortality Rate and Life Expectancy Class",
#       #      subtitle = "Means not sharing any letter are significantly different at the 5% significance level (Tukey's test)") +
#       geom_text(aes(label=cld3$Letters), nudge_x = 0.25, nudge_y = 5, size = 3) +
#         theme_minimal())
```
```{r Chart 6}
plot_ly(dt3, x = ~life_expect_class, y = ~mean_mortality_rate, type = 'bar', text = ~cld3$Letters, textposition = "none", colors = c("#16c91f", "hot pink", "#31befd"), color = ~cld3$Letters, error_y = list(array = ~standard_error, color = 'grey')) %>% layout(xaxis = list(title = 'Life Expectancy at Birth Class'), yaxis = list(title = 'Mean COVID-19 Mortality Rate', range = c(0, 185)))
```

### **Chart 7:** Global Life Expectancy at Birth in Relation to Mortality Rate 
```{r Chart 7}
x4 <- ggplot(region_mort_tb1, aes(text = paste("country: ",country), x=life_expectancy_birth, y=mortality_rate, colour=region)) + 
           geom_point() + theme_minimal() + labs(y = "COVID-19 Mortality Rate", x = "Life Expectancy at Birth (years)")
                 
x4 <- ggplotly(x4) 

x4 %>%
  layout(legend = list(title=list(text = "Region"))) %>%
  layout(legend = list(orientation = 'v', x = 0.01, y = 1)) %>%
  layout(legend = list(font = list(size = 9)))
```





