---
title: "An Overview of a Global Pandemic"
author: 'Group 4: Almost the Data Sisters'
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source: embed

---
# Overview

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
covid_df <- readRDS(file="country.info.RDS")
```

Inputs {.sidebar}
-----------------------------------------------------------------------
### Overview 

**COVID-19** is an infectious disease caused by the SARS-CoV-2 virus. The emergence of the COVID-19 global pandemic has received much attention in the scientific world, prompting researchers to actively explore the potential socioeconomic factors affecting the spread of COVID-19 and and mortality rates. 

This dashboard is intended to provide a visual representation of selected socioeconomic 
factors that may impact the spread of the disease as well as mortality rates across countries. 

**How to Use:** The interactive map on the right provides country-specific status relating to COVID-19. You may click to drag the map around, or click the '+' and '-' buttons to zoom in and out. You may hover over countries to reveal a popup with information about the specific country. 

Row {data-height=150}
-----------------------------------------------------------------------

### Value: Total Cases

```{r}
total_confirmed <- sum(covid_df$confirmed, na.rm=TRUE)
flexdashboard::valueBox(formatC(total_confirmed, format = "d", big.mark = ","), 
                        caption = 'Total Confirmed Cases to Date',
                        icon = "fas fa-capsules",
                        color = "#fcbe42")
```


### Value: Total Deaths
```{r}
total_deaths <- sum(covid_df$deaths, na.rm=TRUE)
flexdashboard::valueBox(formatC(total_deaths, format = "d", big.mark = ","),
                        caption = 'Total Deaths',
                        icon = "fas fa-bed",
                        color = "#86dff7")
```


### Value: Reported Recoveries
```{r}
total_recovered <- sum(covid_df$recovered, na.rm=TRUE)
flexdashboard::valueBox(formatC(total_recovered, format = "d", big.mark = ","),
                        caption = 'Reported Recoveries',
                        icon = "fas fa-heart",
                        color = "#95d468")
```

Row {.tabset}
-----------------------------------------------------------------------

### Global Summary: Confirmed Cases

```{r spdf_data}
library(leaflet)
library(rgdal)
library(dplyr)
library(RColorBrewer)

# Download world shape file 
download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip", destfile=paste0(getwd(), "/world_shape_file.zip"))


# Read shape file with rgdal into a spdf (spatial polygon dataframe) object 
world_spdf <- readOGR( 
  dsn= paste0(getwd(),"/world_shape_file/") , 
  layer="TM_WORLD_BORDERS_SIMPL-0.3",
  verbose=FALSE)
```


```{r combine_data}
# Clean & prepare covid_df for merging
covid_df <- covid_df %>%
  rename("ISO3" = "iso3c") %>%
  # Select columns of interest
  select(ISO3, confirmed, deaths, recovered, morbidity_rate, mortality_rate, recovery_rate)

# Combine spdf & covid_df datasets based on ISO3 code
world_spdf_join <- merge(world_spdf, covid_df, by="ISO3")

# Clean the data object
world_spdf_join@data$confirmed <- as.numeric(as.character(world_spdf_join@data$confirmed)) / 1000000 %>% round(2)
world_spdf_join@data$deaths <- as.numeric(as.character(world_spdf_join@data$deaths)) / 1000 %>% round(2)
```


```{r map_confirmed}
# Create a color palette with handmade bins
mybins <- c(0, 1, 5, 10, 20, 50, Inf)
mypalette <- colorBin(palette="YlOrBr",
                      domain=world_spdf_join@data$confirmed,
                      na.color="transparent",
                      bins=mybins)

# Prepare text for popup
mytext <- paste(
    "Country: ", world_spdf_join@data$NAME,"<br/>", 
    "Confirmed Cases (M): ", round(world_spdf_join@data$confirmed, 2), "<br/>", 
    "Morbidity Rate: ", world_spdf_join@data$morbidity_rate, 
    sep="") %>%
  lapply(htmltools::HTML)

# Plot choropleth map with leaflet
m <- leaflet(world_spdf_join) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng=0, lat=30, zoom=2) %>%
  addPolygons(fillColor = ~mypalette(confirmed), 
              stroke = FALSE,
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              weight = 0.3,
              color = "white",
              label = mytext,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "13px",
                direction = "auto"
              )
  ) %>%
  
  # Add legend to the map
  addLegend(pal = mypalette, 
            values = ~confirmed, 
            opacity=0.9, 
            title = "COVID-19 Confirmed Cases (M)", 
            position = "bottomleft")

m
```

### Deaths

```{r map_deaths}
# Create a color palette with handmade bins
mybins <- c(0, 1, 10, 30, 50, 100, 500, Inf)
mypalette <- colorBin(palette="YlGnBu",
                      domain=world_spdf_join@data$deaths,
                      na.color="transparent",
                      bins=mybins)

# Prepare text for popup
mytext <- paste(
    "Country: ", world_spdf_join@data$NAME,"<br/>", 
    "Deaths (K): ", round(world_spdf_join@data$deaths, 2), "<br/>", 
    "Mortality Rate: ", world_spdf_join@data$mortality_rate, 
    sep="") %>%
  lapply(htmltools::HTML)

# Plot choropleth map with leaflet
m <- leaflet(world_spdf_join) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng=0, lat=30, zoom=2) %>%
  addPolygons(fillColor = ~mypalette(deaths), 
              stroke = FALSE,
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              weight = 0.3,
              color = "white",
              label = mytext,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "13px",
                direction = "auto"
              )
  ) %>%
  
  # Add legend to the map
  addLegend(pal = mypalette, 
            values = ~deaths, 
            opacity=0.9, 
            title = "COVID-19 Deaths (K)", 
            position = "bottomleft" )

m
```

# Regional Data

Inputs {.sidebar}
-----------------------------------------------------------------------




# Socioeconomic Data

Inputs {.sidebar}
-----------------------------------------------------------------------


# About
Row {.tabset}
-----------------------------------------------------------------------

### Dashboard

### Data Source

### Packages

The following packages were used to construct the dashboard:

* flexdashboard
* leaflet

Row {data-height=700}
-----------------------------------------------------------------------
### Dataset
    
```{r}
DT::datatable(
  covid_df,
  filter = "top",
  extensions = "Scroller",
  rownames = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%",
  options = list(deferRender = TRUE, scrollY = 300, scroller = TRUE))
```








